- name: Check and install poetry if necessary
  include_role:
    name: ensure-python-command
  vars:
    ensure_python_command_name: poetry
    ensure_python_command_version: "{{ ensure_poetry_version }}"
    ensure_python_command_existing: "{{ ensure_poetry_executable | default('') }}"
    ensure_python_command_venv_path: "{{ ensure_poetry_venv_path }}"
    ensure_python_command_global_symlink: "{{ ensure_poetry_global_symlink }}"

- name: Export ensure_poetry_executable path
  set_fact:
    ensure_poetry_executable: "{{ ensure_python_command_executable }}"
    cacheable: true
