- name: Verify repository names
  when: |
    container_registry_credentials is defined
    and zj_image.dest_registry not in container_registry_credentials
  fail:
    msg: "{{ zj_image.dest_registry }} credentials not found"

- name: Verify repository permission
  when: |
    container_registry_credentials[zj_image.dest_registry].repository is defined and
    not zj_image.dest_repository | regex_search(container_registry_credentials[zj_image.dest_registry].repository)
  fail:
    msg: "{{ zj_image.repository }} not permitted by {{ container_registry_credentials[zj_image.dest_registry].repository }}"

- name: Log in to registry
  command: "skopeo login -u {{ container_registry_credentials[zj_image.dest_registry].username }} -p {{ container_registry_credentials[zj_image.dest_registry].password }} {{ zj_image.dest_registry }}"
  no_log: true

- name: Copy image
  block:
    - name: "Copy to {{ zj_image.dest_repository }}:{{ zj_image.dest_tag }}"
      command: "skopeo copy --all docker://{{ zj_image.src_repository }}:{{ zj_image.src_tag }} docker://{{ zj_image.dest_repository }}:{{ zj_image.dest_tag }}"
  always:
    - name: Log out of registry
      command: "skopeo logout {{ zj_image.dest_registry }}"
