# This job inherits from a buildset-registry job, so it should already
# be running locally and have any speculative images loaded into it.
- hosts: all
  vars:
    # Test that podman works when we're using podman, and docker
    # when we're using docker.
    test_image_source: >-
      {{ 'containers-storage:localhost/zuul/testimage:latest'
         if (container_command == 'podman'
             and not ensure_podman_socket | default(false) | bool)
         else 'docker-daemon:zuul/testimage:latest' }}
    # If we've enabled the podman socket, exercise it.
    # CONTAINER_HOST is like the DOCKER_HOST zuul-quck-start uses
    # but for the podman build
    test_registry_env: "{{ {'CONTAINER_HOST': 'unix:///run/podman/podman.sock'} if ensure_podman_socket | default(false) | bool else {} }}"
    # skopeo weirdly does not honor CONTAINER_HOST. Why? I dunno man.
    # So on skopeo we have to do it via cli.
    test_registry_copy_args: "{{ '--src-daemon-host unix:///run/podman/podman.sock' if ensure_podman_socket | default(false) | bool else '' }}"
  tasks:
    - name: Load real buildset registry connection info
      set_fact:
        real_buildset_registry: "{{ (lookup('file', zuul.executor.result_data_file) | from_json)['secret_data']['buildset_registry'] }}"
      no_log: true
    # This should now use the speculative image, because we've already
    # run use-buildset-registry.
    - name: Run the fake buildset registry
      include_role:
        name: run-buildset-registry
      vars:
        buildset_registry_root: "{{ ansible_user_dir }}/fake_buildset_registry"
        buildset_registry_port: 9000
    # Leave that zuul return so that dependent jobs use the fake one
    - name: Load fake buildset registry connection info
      set_fact:
        fake_buildset_registry: "{{ (lookup('file', zuul.executor.result_data_file) | from_json)['secret_data']['buildset_registry'] }}"
      no_log: true
    - name: Build a test image
      command: "{{ container_command }} build . -t zuul/testimage:latest"
      args:
        chdir: "{{ zuul.project.src_dir }}/test-playbooks/registry/docker"
      environment: "{{ test_registry_env }}"
    - name: Push test image into fake buildset registry
      command: "skopeo copy {{ test_registry_copy_args }} --dest-tls-verify=false --dest-creds {{ buildset_registry.username }}:{{ buildset_registry.password }} {{ test_image_source }} docker://localhost:9000/zuul/docker-testimage:latest"
    - name: Push test image into fake buildset registry
      command: "skopeo copy {{ test_registry_copy_args }} --dest-tls-verify=false --dest-creds {{ buildset_registry.username }}:{{ buildset_registry.password }} {{ test_image_source }} docker://localhost:9000/quay.io/zuul/quay-testimage:latest"
    - name: Pause the job
      zuul_return:
        data:
          zuul:
            pause: true
