- name: Create docker directory
  become: yes
  file:
    state: directory
    path: /etc/docker
    mode: 0755

- name: Install dockerhub proxy configuration
  become: yes
  template:
    dest: /etc/docker/daemon.json
    group: root
    mode: 0644
    owner: root
    src: daemon.json.j2
