- name: Promote container image with tags
  when: promote_container_image_method|default('tag') == 'tag'
  include_tasks: promote-from-tag.yaml

- name: Promote container image with intermediate registry
  when: promote_container_image_method|default('tag') == 'intermediate-registry'
  fail:
    msg: 'The intermediate-registry promote role is not yet complete'
