- name: Verify repository names
  when: |
    container_registry_credentials is defined
    and zj_image.registry not in container_registry_credentials
  loop: "{{ container_images }}"
  loop_control:
    loop_var: zj_image
  fail:
    msg: "{{ zj_image.registry }} credentials not found"

- name: Log in to registry
  no_log: true
  command: >-
    skopeo login {{ zj_image.registry }} -u {{ container_registry_credentials[zj_image.registry].username }} -p {{ container_registry_credentials[zj_image.registry].password }}
  register: result
  until: result.rc == 0
  retries: 3
  delay: 30

- name: Promote image
  loop: "{{ container_images }}"
  loop_control:
    loop_var: zj_image
  include_tasks: promote-retag.yaml

# The docker roles prune obsolete tags here, but that relies on a
# timestamp to make sure we're not deleting in-progress tags (that the
# gate pipeline may be uploading at the same time we're promoting).
# That timestamp is not available with skopeo list-tags, so some other
# mechanism will need to be devised to clean them up.  In the
# meantime, we hope that the cleanup in promote-retag succeeds.
