- hosts: all
  vars:
    upload_container_image_promote: true
    upload_docker_image_promote: true
  tasks:
    - name: Include build tasks
      include_tasks: test-build-container-image-inner.yaml
