- hosts: all
  tasks:
    - name: Set docker_registry cacheable facts
      set_fact:
        cacheable: true
        docker_registry: "localhost"
        docker_credentials:
          username: zuul
          password: testpassword
          repository: testrepo
        container_registry_credentials:
          localhost:
            username: zuul
            password: testpassword
            repository: testrepo

    - name: Install container system
      include_role:
        name: "ensure-{{ container_command }}"

    - name: Install skopeo
      include_role:
        name: "ensure-skopeo"

    - name: Enable insecure registries for podman
      block:
        - name: Create podman configration directory
          become: true
          file:
            state: directory
            path: /etc/containers
            mode: 0755

        - name: Setup insecure registries
          become: true
          copy:
            dest: /etc/containers/registries.conf
            content: |
              [registries.insecure]
              registries = ['localhost']
            mode: 0644
      when: container_command == 'podman'

    - name: Enable insecure registries for docker
      block:
        - name: Setup insecure registries for docker
          include_role:
            name: update-json-file
          vars:
            update_json_file_name: /etc/docker/daemon.json
            update_json_file_combine:
              insecure-registries:
                - localhost
            update_json_dir_mode: 0755
            update_json_file_mode: 0644
            update_json_file_owner: root
            update_json_file_group: root
            update_json_file_become: true

        - name: Stop docker.socket to avoid any conflict
          become: true
          service:
            name: docker.socket
            enabled: yes
            state: stopped
          failed_when: false

        - name: Assure docker service is restarted
          become: true
          service:
            name: docker
            enabled: yes
            state: restarted

        - name: Assure docker.socket service is running
          become: true
          service:
            name: docker.socket
            enabled: yes
            state: started
          failed_when: false
      when: container_command == 'docker'

    - name: Set up a publication registry to stand in for Docker Hub
      import_tasks: ../../util-tasks/run-docker-registry.yaml
      vars:
        registry:
          host: "127.0.0.1"
          port: 80
          username: zuul
          password: testpassword
        container_command: docker
