- name: Check and install pyproject-build if necessary
  include_role:
    name: ensure-python-command
  vars:
    ensure_python_command_name: pyproject-build
    ensure_python_command_package: build
    ensure_python_command_version: "{{ ensure_pyproject_build_version }}"
    ensure_python_command_existing: "{{ ensure_pyproject_build_executable | default('') }}"
    ensure_python_command_venv_path: "{{ ensure_pyproject_build_venv_path }}"
    ensure_python_command_global_symlink: "{{ ensure_pyproject_build_global_symlink }}"

- name: Export ensure_pyproject_build_executable path
  set_fact:
    ensure_pyproject_build_executable: "{{ ensure_python_command_executable }}"
    cacheable: true
