- hosts: all
  vars:
    test_aws_access_key: minioadmin
    test_aws_secret_key: minioadmin
    test_bucket: zuul
    test_image: "image"
    test_filename: "/tmp/testfile"
    test_objectname_old: "image-old.raw"
    test_objectname: "image.raw"
    test_ext: "raw"
    test_content: "123abc"
  roles:
    - ensure-docker
    - ensure-pip
  tasks:
    - name: Install zstd
      become: true
      package:
        state: present
        name:
          - zstd

    - name: Install boto
      pip:
        extra_args: "--break-system-packages"
        name:
          - boto3
          - botocore

    - name: Start minio server
      command: >-
        docker run -d -p 9000:9000
        -e MINIO_ACCESS_KEY={{ test_aws_access_key }}
        -e MINIO_SECRET_KEY={{ test_aws_secret_key }}
        docker.io/pgsty/silo server /data

    - name: Make sure bucket exists
      s3_bucket:
        name: "{{ test_bucket }}"
        state: present
        s3_url: 'http://localhost:9000'
        aws_access_key: "{{ test_aws_access_key }}"
        aws_secret_key: "{{ test_aws_secret_key }}"

    - name: Add content to tempfile
      copy:
        content: "{{ test_content }}"
        dest: "{{ test_filename }}"

    - name: Upload file to s3
      include_role:
        name: upload-image-s3
      vars:
        upload_image_s3_endpoint: "http://localhost:9000"
        upload_image_s3_aws_access_key: "{{ test_aws_access_key }}"
        upload_image_s3_aws_secret_key: "{{ test_aws_secret_key }}"
        upload_image_s3_bucket: "{{ test_bucket }}"
        upload_image_s3_filename: "{{ test_filename }}"
        upload_image_s3_name: "{{ test_objectname_old }}"
        upload_image_s3_image_name: "{{ test_image }}"
        upload_image_s3_format: "{{ test_ext }}"
        upload_image_s3_delete_after: 1

    - name: Delay for 5 seconds
      wait_for:
        timeout: 5

    - name: Add content to tempfile
      copy:
        content: "{{ test_content }}"
        dest: "{{ test_filename }}"

    - name: Remove temp file so we can run the role again
      command: rm -f /tmp/testfile.zst

    # This should delete the first object then replace it.
    - name: Upload file to s3
      include_role:
        name: upload-image-s3
      vars:
        upload_image_s3_endpoint: "http://localhost:9000"
        upload_image_s3_aws_access_key: "{{ test_aws_access_key }}"
        upload_image_s3_aws_secret_key: "{{ test_aws_secret_key }}"
        upload_image_s3_bucket: "{{ test_bucket }}"
        upload_image_s3_filename: "{{ test_filename }}"
        upload_image_s3_name: "{{ test_objectname }}"
        upload_image_s3_image_name: "{{ test_image }}"
        upload_image_s3_format: "{{ test_ext }}"
        upload_image_s3_delete_after: 1

    - name: Create mcli download destination
      file:
        state: directory
        path: "{{ ansible_user_dir }}/mcli"
        mode: 0755

    - name: Download mcli
      get_url:
        url: https://github.com/pgsty/mc/releases/download/RELEASE.2026-09-13T00-00-00Z/mcli_20260913000000.0.0_linux_amd64.tar.gz
        dest: "{{ ansible_user_dir }}/mcli/mcli.tar.gz"
        mode: 0644

    - name: Extract mcli
      unarchive:
        src: "{{ ansible_user_dir }}/mcli/mcli.tar.gz"
        remote_src: yes
        dest: "{{ ansible_user_dir }}/mcli/"
        include:
          - mcli
        creates: "{{ ansible_user_dir }}/mcli/mcli"

    - name: Add localhost minio host
      command: "{{ ansible_user_dir }}/mcli/mcli alias set local http://localhost:9000 {{ test_aws_access_key }} {{ test_aws_secret_key }}"

    - name: List files in minio bucket
      command: "{{ ansible_user_dir }}/mcli/mcli find local/zuul"

    - name: Check for testfile in minio bucket
      command: "{{ ansible_user_dir }}/mcli/mcli find local/zuul/{{ test_objectname }}.zst"

    - name: Add content to tempfile
      copy:
        content: "{{ test_content }}"
        dest: "{{ test_filename }}"

    - name: Remove temp file so we can run the role again
      command: rm -f /tmp/testfile.zst

    # This should upload the raw image w/o compressing it
    - name: Upload file to s3
      include_role:
        name: upload-image-s3
      vars:
        upload_image_s3_endpoint: "http://localhost:9000"
        upload_image_s3_aws_access_key: "{{ test_aws_access_key }}"
        upload_image_s3_aws_secret_key: "{{ test_aws_secret_key }}"
        upload_image_s3_bucket: "{{ test_bucket }}"
        upload_image_s3_filename: "{{ test_filename }}"
        upload_image_s3_name: "{{ test_objectname }}"
        upload_image_s3_image_name: "{{ test_image }}"
        upload_image_s3_format: "{{ test_ext }}"
        upload_image_s3_compress_image: false

    - name: Check for testfile in minio bucket
      command: "{{ ansible_user_dir }}/mcli/mcli find local/zuul/{{ test_objectname }}"
