- name: Install podman
  package:
    name: "{{ ensure_podman_rootless | bool | ternary(_ensure_podman_rootless_packages, _ensure_podman_packages) }}"
    state: present
  become: yes
  vars:
    _ensure_podman_packages:
      - podman
      - uidmap
      - slirp4netns
      - containernetworking-plugins
    _ensure_podman_rootless_packages:
      - podman
      - passt
      - uidmap
      - netavark
      - aardvark-dns
      - crun
      - runc
