- name: Install podman
  package:
    name: "{{ ensure_podman_rootless | bool | ternary(_ensure_podman_rootless_packages, _ensure_podman_packages) }}"
    state: present
  become: yes
  vars:
    _ensure_podman_packages:
      - 'podman=3.4.4+ds1-1ubuntu1'
      - uidmap
      - slirp4netns
      - fuse-overlayfs
      - containernetworking-plugins
      # This enables container network dns resolution:
      - golang-github-containernetworking-plugin-dnsname
    _ensure_podman_rootless_packages:
      - podman
      - passt
      - uidmap
      - netavark
      - aardvark-dns
      - crun
      - runc
      - nftables

- name: Force cgroup manager to cgroupfs for Ubuntu
  set_fact:
    ensure_podman_cgroup_manager: cgroupfs
