- name: Install podman
  package:
    name: "{{ ensure_podman_rootless | bool | ternary(_ensure_podman_rootless_packages, _ensure_podman_packages) }}"
    state: present
  become: yes
  vars:
    _ensure_podman_packages:
      - podman
      - crun
      - passt
      - uidmap
      - aardvark-dns
      - nftables
      - catatonit
    _ensure_podman_rootless_packages:
      - podman
      - crun
      - passt
      - uidmap
      - aardvark-dns
      - nftables
      - catatonit
