- name: Create containers config dir
  file:
    path: "{{ ansible_user_dir }}/.config/containers"
    state: directory
    mode: "0755"

- name: Configure user containers.conf
  template:
    src: containers.conf.j2
    dest: "{{ ansible_user_dir }}/.config/containers/containers.conf"
    mode: "0644"
