- name: Check and install twine if necessary
  include_role:
    name: ensure-python-command
  vars:
    ensure_python_command_name: twine
    ensure_python_command_version: "{{ ensure_twine_version }}"
    ensure_python_command_existing: "{{ pypi_twine_executable | default('') }}"
    ensure_python_command_venv_path: "{{ ensure_twine_venv_path }}"
    ensure_python_command_global_symlink: "{{ ensure_twine_global_symlink }}"

- name: Export pypi_twine_executable path
  set_fact:
    pypi_twine_executable: "{{ ensure_python_command_executable }}"
    cacheable: true
