- name: Ensure repository is specified
  assert:
    that: remove_registry_tag_repository is defined

- name: Validate remove_registry_tag_repository is full "url"
  when:
    - "'/' not in remove_registry_tag_repository"
  fail:
    msg: "{{ remove_registry_tag_repository }} must be a full container image url including registry location"

- name: Parse out repo path from full "url"
  set_fact:
    _registry: "{{ (remove_registry_tag_repository | split('/', 1)).0 }}"
    _repopath: "{{ (remove_registry_tag_repository | split('/', 1)).1 }}"

- name: Verify registry names
  when: |
    container_registry_credentials is defined
    and _registry not in container_registry_credentials
  fail:
    msg: "{{ _registry }} credentials not found"

- name: Autoprobe for quay.io
  when:
    - container_registry_credentials[_registry].type is not defined
    - '"quay.io" in _registry'
  set_fact:
    registry_type: "quay"

- name: Autoprobe for docker
  when:
    - container_registry_credentials[_registry].type is not defined
    - '"docker.io" in _registry'
  set_fact:
    registry_type: "docker"

- name: Use explicit registry type if set
  when: container_registry_credentials[_registry].type is defined
  set_fact:
    registry_type: container_registry_credentials[_registry].type

- name: Remove tags
  include_tasks: '{{ registry_type }}.yaml'
