- name: Check and install uv if necessary
  include_role:
    name: ensure-python-command
  vars:
    ensure_python_command_name: uv
    ensure_python_command_version: "{{ ensure_uv_version }}"
    ensure_python_command_existing: "{{ ensure_uv_executable | default('') }}"
    ensure_python_command_venv_path: "{{ ensure_uv_venv_path }}"
    ensure_python_command_global_symlink: "{{ ensure_uv_global_symlink }}"

- name: Export ensure_uv_executable path
  set_fact:
    ensure_uv_executable: "{{ ensure_python_command_executable }}"
    cacheable: true
