- name: Check and install nox if necessary
  include_role:
    name: ensure-python-command
  vars:
    ensure_python_command_name: nox
    ensure_python_command_version: "{{ ensure_nox_version }}"
    ensure_python_command_existing: "{{ nox_executable | default('') }}"
    ensure_python_command_venv_path: "{{ nox_venv_path }}"
    ensure_python_command_global_symlink: false  # not supported

- name: Export nox_executable path
  set_fact:
    nox_executable: "{{ ensure_python_command_executable }}"
    cacheable: true
